/**************************************************************************************************
 * Copyright (c) 2018 TheSledgeHammer.                                                            *
 * All rights reserved. This program and the accompanying materials                               *
 * are made available under the terms of the GNU Lesser Public License v3                         *
 * which accompanies this distribution, and is available at                                       *
 * http://www.gnu.org/licenses/lgpl-3.0.txt                                                       *
 **************************************************************************************************/

package com.thesledgehammer.groovymc.config


import com.thesledgehammer.groovymc.GroovyMC
import com.thesledgehammer.groovymc.utils.StringTools
import net.minecraft.util.text.TextFormatting
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent

class Constants {

    static final String MOD_NAME = "GroovyMC";
    static final String MOD_ID = GroovyMC.MOD_ID;
    static final String VERSION = GroovyMC.VERSION;
    static final String AUTHOR = "TheSledgeHammer";

    static final String MOD_PATH = "src/main";
    static final String RESOURCE_PATH = "resources/assets";
    static final String URL = "com/sledgehammer";

    static final String TEXTURE_PATH_BLOCKS = "textures/blocks";
    static final String TEXTURE_PATH_ITEMS = "textures/items";
    static final String TEXTURE_PATH_FLUIDS = "textures/fluids"
    static final String TEXTURE_PATH_GUI = "textures/gui";

    static final String MODEL_PATH_BLOCKS = "models/block";
    static final String MODEL_PATH_ITEMS = "models/item";

    static final String JAVA_JVM = "java";
    static final String GROOVY_JVM = "groovy";
    static final String SCALA_JVM = "scala";
    static final String KOTLIN_JVM = "kotlin";

    //mcmod.info
    private static final String MOD_INFO_MOD_NAME = StringTools.formatTextColor(MOD_NAME, TextFormatting.DARK_AQUA);
    private static final String  DESCRIPTION = "An Apache Groovy Compatibility Library";
    private static final List<String> AUTHORS_LIST = new ArrayList<>();
    private static final String  CREDITS = "Apache Groovy";
    private static final String WEBSITE = "https://github.com/TheSledgeHammer";
    private static final String LOGO = "GroovyMCLogo.jpg";

    static void setMCModInfo(FMLPreInitializationEvent event) {
        event.getModMetadata().autogenerated = false;
        event.getModMetadata().modId = MOD_ID;
        event.getModMetadata().name = MOD_INFO_MOD_NAME;
        event.getModMetadata().description = DESCRIPTION;
        event.getModMetadata().version = VERSION;
        event.getModMetadata().authorList = AUTHORS_LIST;
        event.getModMetadata().credits = CREDITS;
        event.getModMetadata().url = WEBSITE;
        event.getModMetadata().logoFile = LOGO;
        AuthorsList();
    }

    //List of Authors of this Mod
    private static void AuthorsList() {
        AUTHORS_LIST.add(AUTHOR);
    }
}
