/*
 * Copyright [2018] [TheSledgeHammer]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.thesledgehammer.groovymc.config

import com.thesledgehammer.groovymc.utils.StringTools
import net.minecraft.util.text.TextFormatting
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent

//GroovyMC's mcmod.info
class MCMod {

    private static final String MOD_INFO_MOD_NAME = StringTools.formatTextColor(Constants.MOD_NAME, TextFormatting.DARK_AQUA);
    private static final String  DESCRIPTION = "An Apache Groovy Compatibility Library";
    private static final List<String> AUTHORS_LIST = new ArrayList<>();
    private static final String  CREDITS = "Apache Groovy";
    private static final String WEBSITE = "https://github.com/TheSledgeHammer/GroovyMC";
    private static final String LOGO = "GroovyMCLogo.jpg";

    static void Info(FMLPreInitializationEvent event) {
        event.getModMetadata().autogenerated = false;
        event.getModMetadata().modId = Constants.MOD_ID;
        event.getModMetadata().name = MOD_INFO_MOD_NAME;
        event.getModMetadata().description = DESCRIPTION;
        event.getModMetadata().version = Constants.VERSION;
        event.getModMetadata().authorList = AUTHORS_LIST;
        event.getModMetadata().credits = CREDITS;
        event.getModMetadata().url = WEBSITE;
        event.getModMetadata().logoFile = LOGO;
        AuthorsList();
    }

    //List of Authors of this Mod
    private static void AuthorsList() {
        addAuthor(Constants.AUTHOR);
    }

    private static List<String> Authors() {
        return AUTHORS_LIST;
    }

    private static boolean addAuthor(String authorName) {
        return AUTHORS_LIST.add(authorName)
    }

}
